"""new

Revision ID: 27b8e4a00f2f
Revises: 4d0aca94bccf
Create Date: 2025-02-04 22:45:09.220511

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

from app.core.security import generate_prefix


# revision identifiers, used by Alembic.
revision: str = '27b8e4a00f2f'
down_revision: Union[str, None] = '4d0aca94bccf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'keys', ['key'])
    op.alter_column('users', 'is_verifed',
               existing_type=sa.BOOLEAN(),
               default=False)
    op.alter_column('users', 'is_banned',
               existing_type=sa.BOOLEAN(),
               default=False)
    op.alter_column('users', 'prefix',
               existing_type=sa.VARCHAR(),
               default=generate_prefix())
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'prefix',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('users', 'is_banned',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('users', 'is_verifed',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.drop_constraint(None, 'keys', type_='unique')
    # ### end Alembic commands ###
