"""new. Add new column in User "is_banned"

Revision ID: 2c57869a03f7
Revises: 2ef95c1c8bb3
Create Date: 2025-01-31 20:24:19.029921

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2c57869a03f7'
down_revision: Union[str, None] = '2ef95c1c8bb3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('is_banned', sa.Boolean(), default=False))
    op.alter_column('users', 'is_verifed',
               existing_type=sa.BOOLEAN(),
               default=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'is_verifed',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.drop_column('users', 'is_banned')
    # ### end Alembic commands ###
