"""new. Add column in User 'is_admin'

Revision ID: 5bece584ff4b
Revises: 27b8e4a00f2f
Create Date: 2025-02-08 08:27:49.459127

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

from app.core.security import generate_prefix


# revision identifiers, used by Alembic.
revision: str = '5bece584ff4b'
down_revision: Union[str, None] = '27b8e4a00f2f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('is_admin', sa.Boolean(), default=False))
    op.alter_column('users', 'is_verifed',
               existing_type=sa.BOOLEAN(),
               default=False)
    op.alter_column('users', 'is_banned',
               existing_type=sa.BOOLEAN(),
               default=False)
    op.alter_column('users', 'prefix',
               existing_type=sa.VARCHAR(),
               default=generate_prefix())
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'prefix',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('users', 'is_banned',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('users', 'is_verifed',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.drop_column('users', 'is_admin')
    # ### end Alembic commands ###
