"""new. Add new column 'prefix'

Revision ID: bf2984b052bf
Revises: e344e1f2d5cf
Create Date: 2025-02-04 08:10:40.760047

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

from app.core.security import generate_prefix


# revision identifiers, used by Alembic.
revision: str = 'bf2984b052bf'
down_revision: Union[str, None] = 'e344e1f2d5cf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('prefix', sa.String(), default=generate_prefix()))
    op.alter_column('users', 'email',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('users', 'is_verifed',
               existing_type=sa.BOOLEAN(),
               default=False)
    op.alter_column('users', 'is_banned',
               existing_type=sa.BOOLEAN(),
               default=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'is_banned',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('users', 'is_verifed',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('users', 'email',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('users', 'prefix')
    # ### end Alembic commands ###
