"""new Add column 'email', remove column 'phone'

Revision ID: e344e1f2d5cf
Revises: 2c57869a03f7
Create Date: 2025-02-03 18:04:33.525452

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e344e1f2d5cf'
down_revision: Union[str, None] = '2c57869a03f7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('email', sa.String()))
    op.alter_column('users', 'is_verifed',
               existing_type=sa.BOOLEAN(),
               default=False)
    op.alter_column('users', 'is_banned',
               existing_type=sa.BOOLEAN(),
               default=False)
    op.drop_column('users', 'phone')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('phone', sa.BIGINT(), autoincrement=False))
    op.alter_column('users', 'is_banned',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('users', 'is_verifed',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.drop_column('users', 'email')
    # ### end Alembic commands ###
